<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4k83dxk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4k83dxk/appProdProjectContainer.php') {
    touch(__DIR__.'/Container4k83dxk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container4k83dxk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container4k83dxk\appProdProjectContainer([
    'container.build_hash' => '4k83dxk',
    'container.build_id' => '370741f1',
    'container.build_time' => 1652692725,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4k83dxk');
