<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYzktwme\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYzktwme/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYzktwme.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYzktwme\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYzktwme\appProdProjectContainer([
    'container.build_hash' => 'Yzktwme',
    'container.build_id' => '2f160d1b',
    'container.build_time' => 1652353963,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYzktwme');
