<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOz8n1wb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOz8n1wb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOz8n1wb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOz8n1wb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOz8n1wb\appProdProjectContainer([
    'container.build_hash' => 'Oz8n1wb',
    'container.build_id' => 'b62c1ed0',
    'container.build_time' => 1651749294,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOz8n1wb');
