<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVrala37\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVrala37/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVrala37.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVrala37\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVrala37\appDevDebugProjectContainer([
    'container.build_hash' => 'Vrala37',
    'container.build_id' => '81822168',
    'container.build_time' => 1652775522,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVrala37');
