<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0jiynxn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0jiynxn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0jiynxn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0jiynxn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0jiynxn\appDevDebugProjectContainer([
    'container.build_hash' => '0jiynxn',
    'container.build_id' => '67e04e4c',
    'container.build_time' => 1652692390,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0jiynxn');
